# -*- coding: utf-8 -*-
{
    "name": "TMFC005 Wiring - Product Inventory",
    "summary": "ODA TMFC005 wiring on top of TMF Product Inventory (tmf_product_inventory)",
    "version": "1.0.0",
    "author": "OdooTMFOpenAPI",
    "license": "LGPL-3",
    "category": "TMF/ODA",
    "depends": [
        "tmf_product_inventory",
        "tmf_product_stock_relationship",
        "tmf_product",
        "tmf_product_catalog",
        "tmf_product_ordering",
        "tmf_party_role",
        "tmf_billing_management",
        "tmf_agreement",
        "tmf_service_inventory",
        "tmf_resource_inventory",
        "tmf_geographic_address",
        "tmf_geographic_site",
        "tmf_geographic_location",
        "tmf_process_flow",
        "stock",
    ],
    "data": [],
    "installable": True,
}
