# -*- coding: utf-8 -*-
{
    "name": "TMFC002 Wiring - Product Order Capture and Validation",
    "summary": "ODA TMFC002 wiring on top of TMF622 Product Ordering (tmf_product_ordering)",
    "version": "1.1.0",
    "author": "Joao Nascimento",
    "license": "LGPL-3",
    "category": "TMF/ODA",
    "depends": [
        "tmf_product_ordering",
        "tmf_product_catalog",
        "tmf_party",
        "tmf_party_role",
        "tmf_account",
        "tmf_billing_management",
        "tmf_product_offering_qualification",
        "tmf_shopping_cart",
        "tmf_service_qualification",
        "tmf_quote_management",
        "tmf_agreement",
        "tmf_appointment",
        "tmf_geographic_address",
        "tmf_resource_reservation",
        "tmf_payment",
    ],
    "data": [],
    "installable": True,
}
